[project]
name = "KBio"
version = "0.0.1"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

testpaths = [
    "tests",
]

pythonpath = [
    "src",
]

[tool.setuptools.packages.find]
where = ["src/"]
include = ["KBio"]
